/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minisoccerfieldmanagement.form;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JPanel;
import minisoccerfieldmanagement.tabbed.TabbedForm;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author trank
 */
public class PriceListSetting extends TabbedForm {

    /**
     * Creates new form PriceListSetting
     */
    public PriceListSetting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        crazyPanel2 = new raven.crazypanel.CrazyPanel();
        btnPrint = new javax.swing.JButton();
        flatTabbedPane1 = new com.formdev.flatlaf.extras.components.FlatTabbedPane();
        pnlMon = new raven.crazypanel.CrazyPanel();
        pnlTue = new raven.crazypanel.CrazyPanel();
        pnlWed = new raven.crazypanel.CrazyPanel();
        pnlThu = new raven.crazypanel.CrazyPanel();
        pnlFri = new raven.crazypanel.CrazyPanel();
        pnlSat = new raven.crazypanel.CrazyPanel();
        pnlSun = new raven.crazypanel.CrazyPanel();

        setPreferredSize(new java.awt.Dimension(1188, 696));

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "background:$Table.background;[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20",
            null
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap,fill,insets 15",
            "[fill]",
            "[grow 0][fill]",
            null
        ));

        crazyPanel2.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "background:$Table.background",
            new String[]{
                "JTextField.placeholderText=Search;background:@background",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1",
                "background:lighten(@background,8%);borderWidth:1"
            }
        ));
        crazyPanel2.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "",
            "[]push[][]",
            "",
            new String[]{
                "width 200"
            }
        ));

        btnPrint.setText("5 A SIDE");
        crazyPanel2.add(btnPrint);

        crazyPanel1.add(crazyPanel2);

        flatTabbedPane1.addTab("Mon", pnlMon);
        flatTabbedPane1.addTab("Tue", pnlTue);
        flatTabbedPane1.addTab("Wed", pnlWed);
        flatTabbedPane1.addTab("Thu", pnlThu);
        flatTabbedPane1.addTab("Fri", pnlFri);
        flatTabbedPane1.addTab("Sat", pnlSat);
        flatTabbedPane1.addTab("Sun", pnlSun);

        crazyPanel1.add(flatTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private raven.crazypanel.CrazyPanel crazyPanel2;
    private com.formdev.flatlaf.extras.components.FlatTabbedPane flatTabbedPane1;
    private raven.crazypanel.CrazyPanel pnlFri;
    private raven.crazypanel.CrazyPanel pnlMon;
    private raven.crazypanel.CrazyPanel pnlSat;
    private raven.crazypanel.CrazyPanel pnlSun;
    private raven.crazypanel.CrazyPanel pnlThu;
    private raven.crazypanel.CrazyPanel pnlTue;
    private raven.crazypanel.CrazyPanel pnlWed;
    // End of variables declaration//GEN-END:variables
}
